/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package distributedcomputing;

import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.LineNumberReader;
import java.io.PrintWriter;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import org.jblas.DoubleMatrix;

/**
 *
 * @author spsither
 */
public class MainGUI extends javax.swing.JFrame {

    /**
     * Creates new form Volunteer
     */
    public MainGUI() {
        initComponents();
        jLabel3.setVisible(false);
        jLabel4.setVisible(false);
        jLabel5.setVisible(false);
        unitHub = new UnitHub(7777, jTextArea1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();
        jSeparator1 = new javax.swing.JSeparator();
        jTextField3 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel1.setText("Distributed Computing");

        jTextField1.setEditable(false);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jButton1.setText("Operand 1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Operand 2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "+", "-", "*", "Element Wise Mul" }));

        jButton3.setText("Result");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel2.setText("List of volunteers");

        jButton4.setText("Compute");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("Wellcome");
        jScrollPane2.setViewportView(jTextArea1);

        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("*");

        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setText("*");

        jLabel5.setForeground(new java.awt.Color(255, 0, 0));
        jLabel5.setText("*");

        jTextArea2.setEditable(false);
        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jTextArea2.setText("Voulnteer to port 7777\nof this machine's port number\n(ipconfig getifaddr en1)");
        jScrollPane1.setViewportView(jTextArea2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabel1)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                                                        .addComponent(jTextField2))))
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jButton1)
                                                .addComponent(jButton2))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel3)
                                                .addComponent(jLabel4)))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jButton3))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5))
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING))
                        .addContainerGap(164, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton2)
                        .addComponent(jLabel4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3)
                    .addComponent(jButton4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
         chooser.showOpenDialog(null);
         op1file = chooser.getSelectedFile();
         String filename = op1file.getAbsolutePath();
         jTextField1.setText(filename);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser1 = new JFileChooser();
         chooser1.showOpenDialog(null);
         op2file = chooser1.getSelectedFile();
         String filename1 = op2file.getAbsolutePath();
         jTextField2.setText(filename1);   
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser2 = new JFileChooser();
         chooser2.showOpenDialog(null);
         resultfile = chooser2.getSelectedFile();
         String filename2 =  resultfile.getAbsolutePath();
         jTextField3.setText(filename2); 
    }//GEN-LAST:event_jButton3ActionPerformed

    
    public DoubleMatrix loadMatrixFromDatFile(File file) throws NumberFormatException, IOException, NullPointerException{
    /*
     * Example file format:
     * # name: y
     * # type: matrix
     * # rows: 3862
     * # columns: 5
     */
    DoubleMatrix result = null;
    LineNumberReader lnr;
    
      FileReader fr = new FileReader(file);
      lnr = new LineNumberReader(fr);
      int rows = -1;
      int cols = -1;
      boolean created = false;
      String line;
      int rowc = 0;
      int colc = 0;
      while (true) {
        line = lnr.readLine();
        if (line == null) {
          break;
        }
        if (line.startsWith("#")) {
          String[] tokens = line.split(" ");
          if (tokens[1].equals("rows:")) {
            rows = Integer.parseInt(tokens[2]);
          }
          if (tokens[1].equals("columns:")) {
            cols = Integer.parseInt(tokens[2]);
          }

          if (rows > 0 && cols > 0 && !created) {
            result = new DoubleMatrix(rows, cols);
            created = true;
          }
        } else {
          if (!created) {
            System.err.println("Unexpected non-header read at line "
                + lnr.getLineNumber() + ":" + file);
            throw new IOException("Invalid file format");
          }
          String[] tokens = line.split(" ");

          for (String token : tokens) {
            if (token.equals("")) {
              continue;
            }
            double d = Double.parseDouble(token);
            result.put(rowc, colc, d);
            colc++;
          }
          rowc++;
          colc = 0;
        }
      }

    
    return result;
  }
    
    public void writeMatrixToFile(DoubleMatrix theta, File file) throws IOException, NullPointerException{
        try (PrintWriter w = new PrintWriter( new FileWriter(file))) {       
            w.println("# name: " + file.getName());
            w.println("# type: matrix");
            w.println("# rows: "+theta.rows);
            w.println("# columns: "+theta.columns);
            for(int i = 0; i < theta.rows; i++){
                for(int j = 0; j < theta.columns; j++){
                    w.print(theta.get(i,j)+" ");
                }
                w.println();
            }
        }
  }
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    
       
       
    try{op1 = loadMatrixFromDatFile(op1file);}
    catch(IOException e){ 
        JOptionPane.showMessageDialog(rootPane, "Pleace make sure selected file"
            +" is a matrix of proper format.", "IO Error", JOptionPane.ERROR_MESSAGE);
        jLabel3.setVisible(true);
        return;
    }
    catch(NumberFormatException e){
         JOptionPane.showMessageDialog(rootPane, "Pleace make sure selected file"
            +" is of double number of proper dymension.", "Datatype error", JOptionPane.ERROR_MESSAGE);
        jLabel3.setVisible(true);
        return;
    }
    catch(NullPointerException e){
        JOptionPane.showMessageDialog(rootPane, "Pleace select Operand one.", "File Error", JOptionPane.ERROR_MESSAGE);
        jLabel3.setVisible(true);
        return;
    }
    try{op2 = loadMatrixFromDatFile(op2file);}
    catch(IOException e){ 
        JOptionPane.showMessageDialog(rootPane, "Pleace make sure selected file"
            +" is a matrix of proper format.", "IO Error", 
            JOptionPane.ERROR_MESSAGE);
        jLabel4.setVisible(true);
        return;
    }
    catch(NumberFormatException e){
         JOptionPane.showMessageDialog(rootPane, "Pleace make sure selected file"
            +" is of double number of proper dymension.", "Datatype error",
            JOptionPane.ERROR_MESSAGE);
        jLabel4.setVisible(true);
        return;
    }
    catch(NullPointerException e){
        JOptionPane.showMessageDialog(rootPane, "Pleace select Operand two.", "File Error", JOptionPane.ERROR_MESSAGE);
        jLabel4.setVisible(true);
        return;
    }
    String selection = (String) jComboBox1.getSelectedItem();
    char op = 0;
        switch (selection) {
            case "+":
            case "-":
            case "Element Wise Mul":
                if(selection.equals("Element Wise Mul")){
                    op = 'M';
                }
                else{
                    op = selection.charAt(0);
                }       try{result = unitHub.distributedCalc(op1, op2, op);}
                catch(NumberFormatException e){
                    JOptionPane.showMessageDialog(rootPane, "Pleace make sure operand one and operand two is of same dymention.", "Matrix Dimention mismatch",JOptionPane.ERROR_MESSAGE);
                    jLabel3.setVisible(true);
                    jLabel4.setVisible(true);
                    return;
                }
                catch(Exception e){
                    JOptionPane.showMessageDialog(rootPane, "Pleace make sure you have at least one volunteer.", "No Volunteer Error",JOptionPane.ERROR_MESSAGE);
                    return;
                    //e.printStackTrace();
                }       
                break;
            case "*":
                try{result = unitHub.MatrixMul(op1, op1);}
                catch(NumberFormatException e){
                    JOptionPane.showMessageDialog(rootPane, "Pleace make sure column of "
                            +"operand one and row of operand two are of same length.", "Matrix Dimention mismatch",
                            JOptionPane.ERROR_MESSAGE);
                    jLabel3.setVisible(true);
                    jLabel4.setVisible(true);
                    return;
                }
                catch(Exception e){
                    JOptionPane.showMessageDialog(rootPane, "Pleace make sure you have at least one volunteer.", "No Volunteer Error", JOptionPane.ERROR_MESSAGE);
                    return;
                    //e.printStackTrace();
                }       
                break;
        }
    
    try{writeMatrixToFile(result, resultfile);}
    catch(IOException e){
        JOptionPane.showMessageDialog(rootPane, "Pleace select a proper result file.",
        "File error", 
        JOptionPane.ERROR_MESSAGE);
        return;
    }
    catch(NullPointerException e){
        JOptionPane.showMessageDialog(rootPane, "Pleace select a file for storing result.", "File Error", JOptionPane.ERROR_MESSAGE);
        jLabel5.setVisible(true);
        return;
    }
    
    //
    System.out.println("Matrix op1:");
    for(int i = 0; i < op1.getRows(); i++){
        for(int j = 0; j < op1.getColumns(); j++){
            System.out.print(op1.get(i,j) + " ");
        }System.out.println();
    }
      System.out.println("Matrix op2:");
    for(int i = 0; i < op2.getRows(); i++){
        for(int j = 0; j < op2.getColumns(); j++){
            System.out.print(op2.get(i,j)+ " ");
        }System.out.println();
    }
      System.out.println("Matrix result:");
    for(int i = 0; i < result.getRows(); i++){
        for(int j = 0; j < result.getColumns(); j++){
            System.out.print(result.get(i,j)+ " ");
        }System.out.println();
    }
    System.out.println(op);
    //
    JOptionPane.showMessageDialog(rootPane, "Operation complete!");
    jLabel3.setVisible(false);
    jLabel4.setVisible(false);
    jLabel5.setVisible(false);
         
    
    
        
    }//GEN-LAST:event_jButton4ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
    private File op1file, op2file, resultfile;
    private UnitHub unitHub;
    private DoubleMatrix op1, op2, result;
}
